package com.sitecontroller.sitecontroller.persistence.entity;

public interface IProfile extends ISoftDeleteEntity {

    short MIN_CONFIG_VERSION = 10;
    short MAX_CONFIG_VERSION = 255;

    String getName();
    void setName(String name);
    Byte getTagType();
    void setTagType(Byte tagType);
    Byte getHardwareVersion();
    void setHardwareVersion(Byte hardwareVersion);
    Short getUdpCheckinDelay();
    void setUdpCheckinDelay(Short udpCheckinDelay);
    Short getWifiMode();
    void setWifiMode(Short wifiMode);
    Short getRefTagScanTimeTensOfSeconds();
    void setRefTagScanTimeTensOfSeconds(Short refTagScanTimeTensOfSeconds);
    Short getTemperatureCorrectionFactor();
    void setTemperatureCorrectionFactor(Short temperatureCorrectionFactor);
    byte getConfigVersion();
    void setConfigVersion(byte configVersion);
    String getSsid();
    void setSsid(String ssid);
    Boolean isDhcpEnabled();
    void setDhcpEnabled(Boolean dhcpEnabled);
    Integer getDhcpFailTimeout();
    void setDhcpFailTimeout(Integer dhcpFailTimeout);
    Integer getApScanTimeout();
    void setApScanTimeout(Integer apScanTimeout);
    Integer getJoinBssTimeout();
    void setJoinBssTimeout(Integer joinBssTimeout);
    Integer getCommandListenTimeout();
    void setCommandListenTimeout(Integer commandListenTimeout);
    Byte getSecurityType();
    void setSecurityType(Byte securityType);
    String getWepKey();
    void setWepKey(String wepKey);
    Short getWepKeyIndex();
    void setWepKeyIndex(Short wepKeyIndex);
    String getWpaPassphrase();
    void setWpaPassphrase(String wpaPassphrase);
    String getIpAddress();
    void setIpAddress(String ipAddress);
    String getNetmask();
    void setNetmask(String netmask);
    String getGateway();
    void setGateway(String gateway);
    String getServerIpAddress();
    void setServerIpAddress(String serverIpAddress);
    Integer getServerPort();
    void setServerPort(Integer serverPort);
    Byte getChannel1();
    void setChannel1(Byte channel1);
    Byte getChannel2();
    void setChannel2(Byte channel2);
    Byte getChannel3();
    void setChannel3(Byte channel3);
    Byte getChannel4();
    void setChannel4(Byte channel4);
    Byte getChannel5();
    void setChannel5(Byte channel5);
    String getAdhocSsid();
    void setAdhocSsid(String adhocSsid);
    Byte getAdhocSecurityType();
    void setAdhocSecurityType(Byte adhocSecurityType);
    Boolean isAdhocWepEnabled();
    void setAdhocWepEnabled(Boolean adhocWepEnabled);
    String getAdhocWepKey();
    void setAdhocWepKey(String adhocWepKey);
    Byte getAdhocChannel();
    void setAdhocChannel(Byte adhocChannel);
    String getAdhocIpAddress();
    void setAdhocIpAddress(String adhocIpAddress);
    Integer getAdhocPort();
    void setAdhocPort(Integer adhocPort);
    Short getAdhocCommandListenTimeout();
    void setAdhocCommandListenTimeout(Short adhocCommandListenTimeout);
    Integer getCheckinPeriod();
    void setCheckinPeriod(Integer checkinPeriod);
    Integer getCheckinRetryPeriod();
    void setCheckinRetryPeriod(Integer checkinRetryPeriod);
    Short getRefTagChirpCount();
    void setRefTagChirpCount(Short refTagChirpCount);
    Byte getRefTagChirpPower();
    void setRefTagChirpPower(Byte refTagChirpPower);
    Byte getRefTagChirpChannel();
    void setRefTagChirpChannel(Byte refTagChirpChannel);
    Byte getWifiRate();
    void setWifiRate(Byte wifiRate);
    Short getRefTagLowTimeBetweenChirps();
    void setRefTagLowTimeBetweenChirps(Short refTagLowTimeBetweenChirps);
    Short getRefTagHighTimeBetweenChirps();
    void setRefTagHighTimeBetweenChirps(Short refTagHighTimeBetweenChirps);
    Short getSyncRandomTime();
    void setSyncRandomTime(Short syncRandomTime);
    Integer getChirpListenPopcornTime();
    void setChirpListenPopcornTime(Integer chirpListenPopcornTime);
    Boolean isTamperEnabled();
    void setTamperEnabled(Boolean tamperEnabled);
    Boolean isMotionEnabled();
    void setMotionEnabled(Boolean motionEnabled);
    Boolean isLocationOnCheckinEnabled();
    void setLocationOnCheckinEnabled(Boolean locationOnCheckinEnabled);
    Boolean isAutoForceLocateEnabled();
    void setAutoForceLocateEnabled(Boolean autoForceLocateEnabled);
    Integer getAlarmTimeoutTime();
    void setAlarmTimeoutTime(Integer alarmTimeoutTime);
    Short getGreenLedBatteryStatusDuration();
    void setGreenLedBatteryStatusDuration(Short greenLedBatteryStatusDuration);
    Short getRedLedBatteryStatusDuration();
    void setRedLedBatteryStatusDuration(Short redLedBatteryStatusDuration);
    Short getNumUdpPacketsToSend();
    void setNumUdpPacketsToSend(Short numUdpPacketsToSend);
    Short getBatteryMeasurementFrequency();
    void setBatteryMeasurementFrequency(Short batteryMeasurementFrequency);
    Short getTemperatureMeasurementFrequency();
    void setTemperatureMeasurementFrequency(Short temperatureMeasurementFrequency);
    Byte getMaxRefTags();
    void setMaxRefTags(Byte maxRefTags);
    Byte getMaxAccessPoints();
    void setMaxAccessPoints(Byte maxAccessPoints);
    Long getLfPacket();
    void setLfPacket(Long lfPacket);
    Integer getBatteryLowLevel();
    void setBatteryLowLevel(Integer batteryLowLevel);
    Integer getBatteryCriticalLevel();
    void setBatteryCriticalLevel(Integer batteryCriticalLevel);
    Short getTemperatureHighMeasurementLimit();
    void setTemperatureHighMeasurementLimit(Short temperatureHighMeasurementLimit);
    Short getTemperatureLowMeasurementLimit();
    void setTemperatureLowMeasurementLimit(Short temperatureLowMeasurementLimit);
    Boolean isAlarmPriorityEnabled();
    void setAlarmPriorityEnabled(Boolean alarmPriorityEnabled);
    Short getAlarmButtonTime();
    void setAlarmButtonTime(Short alarmButtonTime);
    Short getReserved5();
    void setReserved5(Short reserved5);
    Short getReserved6();
    void setReserved6(Short reserved6);
    Short getReserved7();
    void setReserved7(Short reserved7);
    Byte getMassNotificationType();
    void setMassNotificationType(Byte massNotificationType);
    Byte getCyclesBetweenMassNotifyBuzz();
    void setCyclesBetweenMassNotifyBuzz(Byte cyclesBetweenMassNotifyBuzz);
    Short getListenWakeupInterval();
    void setListenWakeupInterval(Short listenWakeupInterval);
    Short getReserved11();
    void setReserved11(Short reserved11);
    Short getReserved13();
    void setReserved13(Short reserved13);
    Short getReserved14();
    void setReserved14(Short reserved14);

    /* TO DO 
    ITagMotionSettings getTagMotionSettings();
    void setTagMotionSettings(ITagMotionSettings tagMotionSettings);
    boolean isTagMotionSettingsLoaded();
    ITagFirmware getTagFirmware();
    void setTagFirmware(ITagFirmware tagFirmware);
    boolean isTagFirmwareLoaded();
    */

    IProfile getParentProfile();
    void setParentProfile(IProfile parentProfile);
    boolean isParentProfileLoaded();
    ISite getSite();
    void setSite(ISite site);
    boolean isSiteLoaded();
}
